### ISSUE TITLE
GitHubの使い方記事を読む

### ISSUE THREAD

**Issue by MayaAbe** [CanSat-FUSiON/CanSat_ARS#36]
これ読む
https://github.com/CanSat-FUSiON/CanSat_Fundamentals/blob/main/teach_04_EnvironmentBuilding/01_Git_and_VisualStudioCode.md

**Comment by KyoheiShiota** [comment]
https://github.com/CanSat-FUSiON/CanSat_Fundamentals/blob/main/teach_04_EnvironmentBuilding/01_Git_and_VisualStudioCode.md

**Comment by MayaAbe** [comment]
@KazumaKato 
終わったらこんな感じでメンションして報告しよう

**Comment by KazumaKato** [comment]
@@KazumaKato 
読み終わりました。

**Comment by 22kyugi** [comment]
@KazumaKato 
読み終わりました

**Comment by tkt08** [comment]
@KazumaKato 
読みました
